version: '3.6'

services:

#  nginx:
#    build:
#      context: ./nginx
#    volumes:
#      - ../client_service:/var/www/client_service
#      - ../jsonrpc_service:/var/www/jsonrpc_service
#      - ../rest_service:/var/www/rest_service
#      - ./nginx/templates:/etc/nginx/templates
#    container_name: ${COMPOSE_PROJECT_NAME}-nginx
#    restart: unless-stopped
#    ports:
## 80 порт занят default.conf
#      - "8081:81"
#      - "8083:83"
#      - "8084:84"
#
#
#  php-fpm:
#    build:
#      context: ./php-fpm
#    volumes:
#      - ../client_service:/var/www/client_service
#      - ../jsonrpc_service:/var/www/jsonrpc_service
#      - ../rest_service:/var/www/rest_service
#    container_name: ${COMPOSE_PROJECT_NAME}-php-fpm
#    #depends_on:
#      #- postgres
#    environment:
#          XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
#          PHP_IDE_CONFIG: "serverName=Docker"
#
#
#  php-cli:
#    build:
#      context: ./php-cli
#    volumes:
#      - ../client_service:/var/www/client_service
#      - ../jsonrpc_service:/var/www/jsonrpc_service
#      - ../rest_service:/var/www/rest_service
#    command: sleep 30000
#    container_name: ${COMPOSE_PROJECT_NAME}-php-cli


  grpc-service:
    build:
      context: ../grpc_service
      dockerfile: ../docker/go/Dockerfile
    ports:
      - "8082:82"
    volumes:
      - ../grpc_service:/grpc_service
      - ../proto_messages:/proto_messages
    container_name: ${COMPOSE_PROJECT_NAME}-go
