FROM nginx:1.19-alpine

# эти конфиги загрузятся авоматически (template):
##ADD ./client.conf /etc/nginx/conf.d/client.conf
##ADD ./jsonrpc.conf /etc/nginx/conf.d/jsonrpc.conf
##ADD ./rest.conf /etc/nginx/conf.d/rest.conf

WORKDIR /var/www
