<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

namespace GPBMetadata;

class GrpcService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ñ
grpc_service.protogrpc_service"

GetRequest"ç
GetResponse
str_v (	
bool_v (2
arr_v (2#.grpc_service.GetResponse.ArrVEntry+
	ArrVEntry
key (
value (:8"ã

SetRequest
str_v (	
bool_v (1
arr_v (2".grpc_service.SetRequest.ArrVEntry+
	ArrVEntry
key (
value (:8"ç
SetResponse
str_v (	
bool_v (2
arr_v (2#.grpc_service.SetResponse.ArrVEntry+
	ArrVEntry
key (
value (:82ï
GrpcServiceB
GetSettings.grpc_service.GetRequest.grpc_service.GetResponseB
SetSettings.grpc_service.SetRequest.grpc_service.SetResponseBZ./grpc_service/protobproto3'
        , true);

        static::$is_initialized = true;
    }
}

