<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

namespace Grpc_service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * set 
 *
 * Generated from protobuf message <code>grpc_service.SetRequest</code>
 */
class SetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string str_v = 1;</code>
     */
    protected $str_v = '';
    /**
     * Generated from protobuf field <code>bool bool_v = 2;</code>
     */
    protected $bool_v = false;
    /**
     * Generated from protobuf field <code>map<int64, int64> arr_v = 3;</code>
     */
    private $arr_v;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $str_v
     *     @type bool $bool_v
     *     @type array|\Google\Protobuf\Internal\MapField $arr_v
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string str_v = 1;</code>
     * @return string
     */
    public function getStrV()
    {
        return $this->str_v;
    }

    /**
     * Generated from protobuf field <code>string str_v = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStrV($var)
    {
        GPBUtil::checkString($var, True);
        $this->str_v = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool bool_v = 2;</code>
     * @return bool
     */
    public function getBoolV()
    {
        return $this->bool_v;
    }

    /**
     * Generated from protobuf field <code>bool bool_v = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolV($var)
    {
        GPBUtil::checkBool($var);
        $this->bool_v = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int64, int64> arr_v = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getArrV()
    {
        return $this->arr_v;
    }

    /**
     * Generated from protobuf field <code>map<int64, int64> arr_v = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setArrV($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT64, \Google\Protobuf\Internal\GPBType::INT64);
        $this->arr_v = $arr;

        return $this;
    }

}

